version: 0.2

phases:
  install:
    commands:
      - echo "[install] Verificando ambiente Docker"
      - docker info
  pre_build:
    commands:
      - echo "[pre_build] Preparando build"
  build:
    commands:
      - echo "[build] Construindo imagem Docker com build nativo (GraalVM + Musl)"
      - docker build -t native-build-image -f springboot4-otel-poc/Dockerfile.build springboot4-otel-poc
  post_build:
    commands:
      - echo "[post_build] Extraindo artefato estático"
      - id=$(docker create native-build-image)
      - mkdir -p springboot4-otel-poc/target
      - docker cp $id:/app/target/springboot4-otel-poc springboot4-otel-poc/target/
      - docker rm -v $id
      - ls -lh springboot4-otel-poc/target/springboot4-otel-poc
artifacts:
  files:
    - springboot4-otel-poc/target/springboot4-otel-poc
  discard-paths: yes
