version: 0.2

env:
  shell: bash
  variables:
    JAVA_HOME: /opt/graalvm
    GRAALVM_HOME: /opt/graalvm
    MAVEN_OPTS: -Dmaven.test.skip=true
phases:
  install:
    commands:
      - echo "[install] Configurando toolchain"
      - sudo apt-get update -y
      - sudo apt-get install -y build-essential zlib1g-dev
  - curl -L https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz -o /tmp/graalvm.tar.gz
  - sudo mkdir -p /opt/graalvm
  - sudo tar -xzf /tmp/graalvm.tar.gz -C /opt/graalvm --strip-components=1
  - echo "export GRAALVM_HOME=/opt/graalvm" >> $BASH_ENV
  - echo "export JAVA_HOME=/opt/graalvm" >> $BASH_ENV
  - echo "export PATH=/opt/graalvm/bin:$PATH" >> $BASH_ENV
  - source $BASH_ENV
  - ls -l ${JAVA_HOME}/bin
  - ls -l ${JAVA_HOME}/lib/svm/bin/native-image
  - curl -sSL https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.tar.gz | tar -xz -C /tmp
  - echo "export M2_HOME=/tmp/apache-maven-3.9.9" >> $BASH_ENV
  - echo "export PATH=/tmp/apache-maven-3.9.9/bin:$PATH" >> $BASH_ENV
  - source $BASH_ENV
  - mvn -v
  pre_build:
    commands:
      - echo "[pre_build] Limpando workspace"
      - mvn -version
      - mvn -pl springboot4-otel-poc -am clean
  build:
    commands:
      - echo "[build] Compilando nativamente"
      - mvn -pl springboot4-otel-poc -am -Pnative -DskipTests package
  post_build:
    commands:
      - echo "[post_build] Artefato nativo gerado em springboot4-otel-poc/target"
artifacts:
  files:
    - springboot4-otel-poc/target/*.jar
    - springboot4-otel-poc/target/*
  discard-paths: no
cache:
  paths:
    - /root/.m2/**/*
